### PR TITLE
Add extra option "ignores" to suppress individual linters from golint output

### PR DESCRIPTION
**Pull request by d2r2**

### CODE REVIEW

**Comment by kaste** [comment]
Hi @d2r2!

Generally 👍 on the feature. (For other readers: `golint` cannot be configured so a post-process filter is the (only) way to go.)

Note that I made a PR https://github.com/SublimeLinter/SublimeLinter/pull/1424 against SublimeLinter core which would enable post-filter for all linters but it didn't receive any reaction so far.

For the code review:

1. I don't like the polymorphic type here. I would say, if it's just a list of words we match against the error then I don't see why the user should use the more verbose object notation. What's the advantage of the object notation? Do you expect other values than `trueish`. (A map with only trueish values is usually modeled as a set.)

2. As I see it, the `regex` here https://github.com/SublimeLinter/SublimeLinter-golint/blob/0a62e8263926b9eb03fc717a45c991c213ef7916/linter.py#L6 only captures `message`, `line` and `col`. This basically means `error` and `warning` you check for never have a value. `message` on the other hand doesn't seem to be optional otherwise the regex wouldn't match at all. 

Nit-picks:

For python, if you want to check if a `substr` is in `str`, you don't need to use `find`, literally `if needle in message:` will do the trick (`in` operator overloaded for strings).

For the SublimeLinter interface. 

```
    def split_match(match):
        error = super().split_match(match)  # turn a regex match into an error obj
		if needle in error.message:  # Typical 'dot' notation
			return error  # Take it!
		# Reject it by returning 'None'
		# return None  # python implicitly returns 'None' if it falls through
```

Regards

**Comment by d2r2** [comment]
Hi @kaste!
Thank you for quick review and respond!

1) The idea to use polymorphic approach explained by the situation, when you need to change golint output style back an forth (depending on Go project type). So, you just have to put `false` in front of text signature to disable it, instead of complete deletion of suppress text signature in config. So, in such cases JSON object in config looks more preferable than JSON array.
2) Don't remember why I test not only `message`, but `warning` and `error` as well, but certainly can fix it according to your explanation.
3) I will replace `find` with `<substr> in <str>`, since I'm not the person who can consider himself as an expert in python. Thanks for explanation.
4) Could you give more explanation on code sample provided by you? Do you have recommendations regarding "return" style?

What is your thoughts on 1, 4? Can I move forward with modification 2-3?

**Comment by kaste** [comment]
I would like to wait for @braver here bc of the other PR mentioned https://github.com/SublimeLinter/SublimeLinter/pull/1424

Regarding 1. Fast disabling is also possible with a list. Sublime actually uses 'enhanced' JSON which allows comments. Consider: 

```
{
    "includes": [
        // "ALL",
        "CAPS"
    ]
}
```

Now you could just use the 'Toggle-comment' command from Sublime for fast toggling.

Since we also support project settings, you could also leave the global/default settings as is, and only add some stop-words per project. http://www.sublimelinter.com/en/stable/settings.html#project-settings

**Comment by d2r2** [comment]
@kaste, agree with you and had same thought about commenting this out in JSON array :+1: 
So, let wait for the SublimeLinter/SublimeLinter#1424?

**Comment by braver** [comment]
@kaste So, what this PR does is filter error reports based on the text of the message? I'd like to see this added in core, as per 1424. The implementation there is pretty neat and I think we got rid of a lot of things that made the SL3 version of that feature problematic. And anyway, if we're going to green-light such a feature at all, let's not do it per plugin but globally.

**Comment by kaste** [comment]
@d2r2 Thank you for your PR. As you see, we implemented it in core for all, and bc of that your PR has been closed or "rejected" which sounds a bit harsh 

Regards 👋

**Comment by d2r2** [comment]
@kaste, implementing in core much better than just in single plugin! I have start using this global option in my work, thanks :)

**Pull request closed without merging**
